allow multiple arguments to eliminate unneeded quoting report different warnings for ssh and remote-command errors

diff --git a/scripts/ring-all b/scripts/ring-all
--- a/scripts/ring-all
+++ b/scripts/ring-all
@@ -1,15 +1,21 @@
 #!/usr/bin/env bash
-if [ $# -ne 1 ]
-then
-    echo -e "No arguments were given\nUsuage: `basename $0` \"command to be executed on all ring servers\""
+
+if [ $# -lt 1 ]; then
+    echo "No arguments were given"
+    echo "Usuage: `basename $0` \"command to be executed on all ring servers\""
     exit 65
 fi
 
 SERVERS=$(dig -t txt +short ring.nlnog.net | sed 's/\"//g')
 for host in $SERVERS
 do
-echo "host: $host.ring.nlnog.net"
-ssh -q -t $host.ring.nlnog.net $@ || echo "ERROR: ssh command failed"
-echo ""
+    echo "host: $host.ring.nlnog.net"
+    ssh -q -t $host.ring.nlnog.net $@
+    ret=$?
+    if [ "$ret" = 255 ]; then
+	echo "ERROR: ssh connection failed"
+    elif [ "$ret" != 0 ]; then
+	echo "ERROR: remote command failed"
+    fi
 done
 
